### ISSUE TITLE
Uncaught TypeError: Cannot read property 'done' of undefined

### ISSUE THREAD

**Issue by wroquet** [pushandplay/cordova-plugin-apprate#157]
I'm using the plugin on Android and iOs, 
first i, use the plugin the simpliest way, like this inside a deviceready event : 

```javascript
AppRate.preferences.storeAppURL = {
          ios: 'MYAPPNUMBER',
          android: 'market://details?id=com.app'
      };

      AppRate.promptForRating(false);
```

it works fine but when i'm trying tu put custom messages, i'm getting this error in console : 

```
AppRate.js:98 Uncaught TypeError: Cannot read property 'done' of undefined
    at showDialog (AppRate.js:98)
    at Function.AppRate.promptForRating (AppRate.js:203)
    at Channel.<anonymous> (app.js:136)
    at Channel.fire (cordova.js:822)
    at cordova.js:231
```
this is my final code : 

```javascript
var msg = 'lorem ipsum ....';

AppRate.preferences = {
        openStoreInApp: false,
        displayAppName: '',
        usesUntilPrompt: 3,
        promptAgainForEachNewVersion: false,
        storeAppURL: {
          ios: 'MYAPPNUMBER',
          android: 'market://details?id=com.my.app'
        },
        customLocale: {
          title: 'Vous aimez l\'application ?',
          message: msg,
          cancelButtonLabel: "Non merci",
          laterButtonLabel: "Plus tard",
          rateButtonLabel: "Oui, je donne mon avis"
        }
      };


      AppRate.promptForRating(false);
```
it works fine when i use promptFotRating without false...

**Comment by oangelo** [comment]
I am having the same problem!

**Comment by oangelo** [comment]
@wroquet, I managed to make it work. You must define the callbacks, other wise you will get that error. I have defined then as empty functions and everything is now working as expected. But this is not clear at all at the README. Here is my code in coffeescript:
```
    #ask for user review
    if AppRate
      AppRate.preferences =
        openStoreInApp: true,
        displayAppName: 'Física Básica',
        usesUntilPrompt: 2,
        promptAgainForEachNewVersion: false,
        storeAppURL:
          ios: '<my_app_id>',
          android: 'market://details?id=com.resumosmoveis.mecanica'
        customLocale:
          title: "Avalie o nosso APP!",
          message: "Nossa equipe está sempre trabalhando para deixar este APP cada vez melhor. Você poderia avaliar nosso APP e deixar uma msg de incentivo para equipe? Sua opinião e incentivo são muito importantes!",
          cancelButtonLabel: "Não, obrigado.",
          laterButtonLabel: "Lembre-me mais tarde.",
          rateButtonLabel: "Avaliar agora!"
        callbacks:
          onButtonClicked: (buttonIndex) ->
              console.log("onButtonClicked -> " + buttonIndex)
          onRateDialogShow: (callback) ->
            return
      AppRate.promptForRating(false)
      console.log("APP Rate")
```
Cleaning the cache and opening the app twice will ask for the user review.

**Comment by westonganger** [comment]
I just released v1.3.0 which fixes this undefined callback issue.

**Comment by carliblaz** [comment]
Strange I user 1.3.0 and I still get this error: Uncaught TypeError: Cannot read property 'done' of undefined

**Comment by jonasblumer** [comment]
I'm also still getting this issue in 1.3.0

**Comment by NBAMj** [comment]
Yeah same issue with 1.3.0

**Comment by staskuban** [comment]
Problem with that code:
```javascript
  showDialog = function(immediately) {
    var base, localeObj;
    if (counter.countdown === AppRate.preferences.usesUntilPrompt || immediately) {
      if (!AppRate.preferences.useCustomRateDialog) {
        localeObj = Locales.getLocale(AppRate.preferences.useLanguage, AppRate.preferences.displayAppName, AppRate.preferences.customLocale);
        navigator.notification.confirm(localeObj.message, promptForRatingWindowButtonClickHandler, localeObj.title, [localeObj.rateButtonLabel, localeObj.laterButtonLabel, localeObj.cancelButtonLabel]);
      }
      if (typeof (base = AppRate.preferences.callbacks).onRateDialogShow === "function") {
        base.onRateDialogShow(promptForRatingWindowButtonClickHandler);
      }
    }else{
      // typeof (base = AppRate.preferences.callbacks).done === "function" ? base.done() : function(){ };
    }
    return AppRate;
  };
```
I don't found usage `done` callback not using in plugin and ionic framework typings so I came to the conclusion that you can bring this code to the next form

```javascript
  showDialog = function(immediately) {
    var base, localeObj;
    if (counter.countdown === AppRate.preferences.usesUntilPrompt || immediately) {
      if (!AppRate.preferences.useCustomRateDialog) {
        localeObj = Locales.getLocale(AppRate.preferences.useLanguage, AppRate.preferences.displayAppName, AppRate.preferences.customLocale);
        navigator.notification.confirm(localeObj.message, promptForRatingWindowButtonClickHandler, localeObj.title, [localeObj.rateButtonLabel, localeObj.laterButtonLabel, localeObj.cancelButtonLabel]);
      }
      if (typeof (base = AppRate.preferences.callbacks).onRateDialogShow === "function") {
        base.onRateDialogShow(promptForRatingWindowButtonClickHandler);
      }
    }
    return AppRate;
  };
```

It helps with error.
