### ISSUE TITLE
Can't rate the app

### ISSUE THREAD

**Issue by rmabunga** [pushandplay/cordova-plugin-apprate#158]
Hi, I am trying to get the rate app plugin to work, but when I clicked the 
"Rate it now" button, I got this error:

Error in Success callbackId: Notification1591841392 : TypeError: undefined is not an object (evaluating '(base = AppRate.preferences.callbacks).onButtonClicked')

My app is not yet deployed to the app store, is there a way to test this functionality 
even if it is not yet on the App Store?

Thank you.

**Comment by westonganger** [comment]
Fixed in latest v1.3.0 release.

**Comment by adappter** [comment]
Still present in v1.3.0

**Comment by Darshan-Chauhan** [comment]
@westonganger , I'm still getting this issue in version 1.4 too

**Comment by Darshan-Chauhan** [comment]
@rmabunga , were you able to solve the problem??

**Comment by Darshan-Chauhan** [comment]
Just FYI, adding callBacks fixed the issue for me.

```
callbacks: {
    handleNegativeFeedback: function(){
      window.open('mailto:feedback@example.com','_system');
    },
    onRateDialogShow: function(callback){
      callback(1) // cause immediate click on 'Rate Now' button
    },
    onButtonClicked: function(buttonIndex){
      console.log("onButtonClicked -> " + buttonIndex);
    }
  }
```

**Comment by LinnielDW** [comment]
@Darshan-Chauhan That worked, now it's not crashing, but now it just doesn't go to the app rate screen :(.

Thanks for the help on this issue though!

**Comment by Darshan-Chauhan** [comment]
@LinnielDW , It'll just open up a link to app store. For iTunes you can have in-app ratings.
