### ISSUE TITLE
can anyone fix this plugin with AppRate.promptForRating(false)

### ISSUE THREAD

**Issue by matrixreal** [pushandplay/cordova-plugin-apprate#270]
Hello,
this plugin is working when we call AppRate.promptForRating(); or AppRate.promptForRating(true);
but when we call AppRate.promptForRating(false); that not work and sometimes work (not stable)
android cordova 6.4.0 (not stable ... working sometimes)
android cordova 7.1.4 (not working at all)
android cordova 8.1.0 (not working at all)
my code is 👍 
AppRate.preferences = {
displayAppName: 'app name',
usesUntilPrompt: 6,
promptAgainForEachNewVersion: true,
inAppReview: false,
simpleMode: true,
storeAppURL: {
android: 'market://details?id=greedy.rabbit.bunny.run'
};
AppRate.promptForRating(false);

thanks

**Comment by NorthFred** [comment]
As a work-around, I am tracking app launches in the `app.component.ts` and store the result to localStorage. If the app launches reaches a certain number (e.g. 6), then I call `AppRate.promptForRating(true);`

Not ideal, but while waiting for a fix, you can use this approach.

**Comment by danielpspring** [comment]
Same issue

**Comment by dharam1986** [comment]
I am also facing the same issue. Do we have any update?

**Comment by westonganger** [comment]
Solved via #289

**Comment by fractalysid** [comment]
any update on this? It is not solved. Same configuration, it never shows the dialog. I'm falling back on writing my own service
